### ISSUE TITLE
Possible typo in TP PFCOL q4

### ISSUE THREAD

**Issue by jemappellesami** [iridia-ulb/INFOH410#5]
Hello,
I think there is a typo in the question 4 of TP PFCOL, for the fifth enumeration of the b). I think it should be "P \vee Q" and not "\neg P \vee Q", because the sentence we have is "P \vee Q".

Yours,
Sami Abdul Sater

**Comment by KenN7** [comment]
Hi,
Thanks a lot for pointing this out ! 
You are right, it is indeed a typo.

Cheers,

(Fixed by a95bab5c0e55adb5ab46ca1d7955a52207d5a0c7)
