### ISSUE TITLE
TP 1 Question 1

### ISSUE THREAD

**Issue by KarolienHeymans** [iridia-ulb/INFOH410#7]
Hello,
I think I found an error in the solution of part b of the first question of TP1. When I run the code, it returns 1 and 2 instead of 3 and 2 as explained in the solution. Is it possible that the lowest value is pushed first instead of the highest? Thank you in advance!

**Comment by KenN7** [comment]
Hi, 
yes, it depends on your implementation of the priority queue.
If its a min-queue it would pop 1 and 2, if its a max-queue it would pop 3 and 2, so both answers are correct given that the question does not say whether the queue should be max or min.

In python, if you used the `heapq` implementation, it is indeed a min-queue.

**Comment by KarolienHeymans** [comment]
Thank you!
